### ISSUE TITLE
bwa mem doesnt start 

### ISSUE THREAD

**Issue by gezthxbio** [rabix/bunny#397] opened 2017-12-15 12:29 UTC
Trying to execute a simple cwl made with composer : bwa index > bwa mem
bwa index step completes and output is generated
bwa mem step doesnt start.

`sudo rabix-cli-1.0.3/rabix bwa_alignv1.cwl -- --input_reads_R1 M12_S2_L001_R1_001.fastq.gz --input_reads_R2 M12_S2_L001_R2_001.fastq.gz --reference Mycobacterium_tuberculosis_h37rv.ASM19595v2.dna.toplevel.fa --threads 32`

output

`2017-12-15 16:23:40.654] [INFO] Job root.bwa_index has started
[2017-12-15 16:23:40.721] [INFO] Pulling docker image images.sbgenomics.com/vladimirk/bwa:0.7.13
[2017-12-15 16:23:41.353] [INFO] Running command line: /opt/bwa-0.7.13/bwa index Mycobacterium_tuberculosis_h37rv.ASM19595v2.dna.toplevel.fa       ; tar -cf Mycobacterium_tuberculosis_h37rv.ASM19595v2.dna.toplevel.fa.tar Mycobacterium_tuberculosis_h37rv.ASM19595v2.dna.toplevel.fa *.amb *.ann *.bwt *.pac *.sa
[2017-12-15 16:23:44.030] [INFO] Job root.bwa_index has completed`
[bwa_alignv1.cwl.txt](https://github.com/rabix/bunny/files/1562648/bwa_alignv1.cwl.txt)

**Comment by milos-ljubinkovic** [comment] 2017-12-26 13:54
Couldn't reproduce this exact issue but it seems that you are missing linkMerge: merge_flatten on the port that has multiple sources if you want them to be merged into a single array. Could you try it with this change?

**Comment by gezthxbio** [comment] 2018-01-02 06:47
You mean to say
 id: bwa_mem_bundle_0_7_13
    in:
      - id: reference_index_tar
        source:
          - bwa_index/indexed_reference
      - id: input_reads
        source:
          - input_reads_R1
          - input_reads_R2
        `linkMerge: merge_flattened`
      - id: threads
        source:
          - threads
    out:
      - id: aligned_reads
      - id: samblaster_log

**Closed** 2018-01-07 10:50 UTC
