### ISSUE TITLE
Better exit control if malformed commandline

### ISSUE THREAD

**Issue by mattions** [rabix/bunny#83] opened 2016-12-14 16:27 UTC
Right now if the two dash are forgotten no error is output and rabix does nothing, however not error is output. I think it should give some infor back to the user

```
mattions@apollo:rabix-backend-local-1.0.0-SNAPSHOT$ ./rabix examples/dna2protein/dna2protein.cwl.json --input_file examples/dna2protein/data/input.txt 
mattions@apollo:rabix-backend-local-1.0.0-SNAPSHOT$ 
```

**Comment by AleksandarPetrovicSBG** [comment] 2016-12-16 11:36
The issue is fixed in v1.0.0-rc2 release.
Feel free to reopen the case if you run into any other problems.

**Closed by AleksandarPetrovicSBG** 2016-12-16 11:36 UTC
