### ISSUE TITLE
Dotproduct scatter method issues

### ISSUE THREAD

**Issue by bogdang989** [rabix/bunny#110] opened 2017-01-26 16:27 UTC
There's a couple of issues encountered while running GDC dna-seq workflow [transform.cwl](https://github.com/NCI-GDC/gdc-dnaseq-cwl/blob/master/workflows/dnaseq/transform.cwl) regarding dotproduct scatter method. [This tool](https://github.com/NCI-GDC/gdc-dnaseq-cwl/blob/master/tools/bwa_pe.cwl) is scattered in the workflow using dotproduct.
1) Single file input is treated as an array with one element
This happens for a file input (fastqc_json_path) which is not one of the inputs used for scattering. 

2) Problem handling output
Dotproduct scatter output returns an error and interrupts workflow execution. This is what it says:

> [2017-01-26 17:03:39.768] [ERROR] EventProcessor failed to process event OutputUpdateEvent [jobId=root.bwa_pe.1, contextId=de3fb3bc-0124-4fc9-bef1-8f8b5275e167, portId=OUTPUT, value=FileValue [size=52984, path=/home/bogdan/Documents/GDC/gdc-dnaseq-cwl-master/workflows/dnaseq/de3fb3bc-0124-4fc9-bef1-8f8b5275e167/root/bwa_pe/1/1.bam, location=/home/bogdan/Documents/GDC/gdc-dnaseq-cwl-master/workflows/dnaseq/de3fb3bc-0124-4fc9-bef1-8f8b5275e167/root/bwa_pe/1/1.bam, checksum=sha1$dffd7a1e88841e7e510d9c266bdc500c4653debf, secondaryFiles=[], properties={sbg:metadata=null}], fromScatter=false, numberOfScattered=null].

3) Secondary files not included
This happens for input fasta. It may have something to do with the fact that secondary files are not listed in the workflow input - id: reference_fasta_path?

**Comment by StarvingMarvin** [comment] 2017-02-02 12:48
This looks like a duplicate of #97

**Comment by simonovic86** [comment] 2017-02-14 17:23
I've fixed it. The fix is on the develop branch.

**Comment by StarvingMarvin** [comment] 2017-02-15 10:28
@bogdang989 Could you please test if rc3 fixed your issues, and reopen them if necessary.

**Closed by StarvingMarvin** 2017-02-15 10:28 UTC
Labels: bug, duplicate

**Comment by bogdang989** [comment] 2017-02-20 16:54
It's fixed, tnx
