### ISSUE TITLE
Update TES backend to match v0.2 schema

### ISSUE THREAD

**Issue by adamstruck** [rabix/bunny#370] opened 2017-10-25 19:52 UTC
@milos-ljubinkovic I am starting an issue to track the state of the TES backend. Is the [refactor/files-and-tes](https://github.com/rabix/bunny/tree/refactor/files-and-tes) branch tracking the most recent work for the TES backend?

I updated the models / http client [here](https://github.com/adamstruck/bunny/tree/tes-models/rabix-backend-tes/src/main/java/org/rabix/backend/tes/model). 

_Questions:_
* For the TES backend, why does rabix need to stage/download the input and output files? Funnel and other TES implementations handle this so it seems unnecessary.

**Comment by milos-ljubinkovic** [comment] 2017-10-26 14:14
Hi @adamstruck 

Yes refactor/files-and-tes is the branch with the latest edits, I was just fixing some stuff related to draft2 and draft3 tests that were failing. I'll create a merge branch and a pull request on develop soon. 

By the way your updated models have some minor issues that I'm correcting. The constructor for TesCreateTaskResponse doesn't assign any value to id (id = id instead of id = value).

Regarding your question about staging:
Inputs are uploaded/copied to the tes-storage path from config if the input paths aren't already there, this should be expanded a bit to only copy/upload if rabbix is sure TES server can't access inputs. 

Outputs are currently downloaded for output collection due to some issues in our file handling. Changing this will take some more time, but I'm sure that soon I'll have it working with collecting outputs in shared storage.

**Comment by adamstruck** [comment] 2017-10-26 23:27
Why does there need to be a TES storage path at all?  You should just be able to provide the URL in `Task.Inputs` and Funnel will handle staging the files for mounting into a docker container.  Similarly for `Task.Outputs` Funnel will also upload (or copy if a shared file system) to a location of your choosing. I am having a hard time thinking of a situation where Bunny would have access to a file and TES would not. 

Is there a requirement for Bunny to introspect the files? If that is the case this makes more sense. In Cromwell, the workflow engine has to localize some files to resolve expressions before creating the TES Task message to send to Funnel.

**Comment by milos-ljubinkovic** [comment] 2017-10-27 09:30
Bunny is usually used as a command line tool with local files, we didn't want to assume that funnel is always going to be installed on the same machine.

Also some CWL workflows have requirements that define the content of the working directory. These files can be defined as a result of some expression so in this case some files have to be created on the storage path.

Currently file processing is done with a simple 'one size fits all' solution, but I'll replace it with a smarter system soon.

**Comment by adamstruck** [comment] 2017-10-27 17:57
Ok now I understand. 

So this means that Bunny cant currently except CWL workflows with inputs in google storage or amazon s3?

**Comment by milos-ljubinkovic** [comment] 2017-10-30 10:53
Google storage for inputs should work now, it would just send the gs:// links to funnel. S3 would cause an exception currently, but I think we will work around that for the next iteration.

**Comment by adamstruck** [comment] 2017-10-31 17:38
If I specify gs://links in the input json for the workflow bunny fails with:

```
org.rabix.bindings.BindingException: org.rabix.bindings.cwl.processor.CWLPortProcessorException: Failed to set input file properties
```

Also I have found that [stageFile](https://github.com/rabix/bunny/blob/develop/rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESWorkerServiceImpl.java#L256) was failing with `org.rabix.backend.tes.service.TESStorageException`.

Tracing the error I found it was failing at the `Files.copy` call here: 
https://github.com/rabix/bunny/blob/develop/rabix-backend-tes/src/main/java/org/rabix/backend/tes/service/impl/LocalTESStorageServiceImpl.java#L96

**Comment by milos-ljubinkovic** [comment] 2017-11-02 12:11
Sorry about that, was a bad merge on develop. I've made a [new branch for tes improvements](https://github.com/rabix/bunny/tree/tes/s3) with simplified file processing. Staging files is only done when they are local and outputs aren't downloaded before they are sent to the next step in a wf. This caused 2 additional tests to fail that rely on output files being local (test-cwl-out and test-cwl-out2), but this can be fixed with something like a configurable callback that will download only terminal outputs (root workflow outputs).

I've also added some basic s3 support (using [my fork of this lib](https://github.com/milos-ljubinkovic/Amazon-S3-FileSystem-NIO2)). This enables using s3:// links as inputs, but I couldn't manage to use s3 as shared storage instead of google cloud because uploading directories isn't supported and funnel throws an exception. Now, this breaks the current way of integration as the working directory is declared as the output of a task and I don't think there is a way to know the the exact outputs before execution is completed. Is there any way in funnel to get the contents of the working folder uploaded to s3, or should I stop with s3 features for now? 

Also I had some problems with getting funnel to download s3 links, but files with `"location":"s3://[bucket name]/path" ` should work

**Comment by adamstruck** [comment] 2017-11-02 16:50
Could you provide some details regarding the issues you ran into with Funnel?

I noticed a small bug - currently it appears that for each CWL file input that is specified, two inputs are created in the resulting TES message. 

The `Outputs` field in the `TaskLogs` (https://github.com/ga4gh/task-execution-schemas/blob/master/task_execution.proto#L250) contains a list of all the output files that Funnel uploaded for the task. 

Looks like you are getting very close to having everything working. Thank you for your continued help!

**Comment by buchanae** [comment] 2017-11-02 17:11
Looking here,
https://github.com/ohsu-comp-bio/funnel/blob/master/storage/s3.go#L178

I think we have added support for directories in the S3 storage backend as of Sept 7, 
https://github.com/ohsu-comp-bio/funnel/commit/83cafcd10213b23b8e7bb17140c1f3720af8c155#diff-52819efd7dd1499ea9ed84ffcce99c8a

Possibly you're using an older version of Funnel?

**Comment by milos-ljubinkovic** [comment] 2017-11-02 17:40
TaskLogs only list the files after they are uploaded,  I was thinking more of a way to list all created files in the docker executor's working directory.

The problem is that actual outputs aren't defined at the moment a cwl task is sent to execution. In the current way of integration I just define the working directory as the only TES output, working dir is uploaded to google storage and then rabbix collects/generates actual outputs from this directory. I couldn't get this to work with s3 instead of google storage because funnel fails to upload directories to to s3. I was just wondering if there is any other way to define outputs or if there are plans for funnel to be able to upload a directory to s3?

Also I couldn't get s3 urls with endpoints to work in funnel. The s3 java library I used generated urls that weren't compatible with funnel so I had to make some changes to it. Some of the links that seem valid to me but funnel had problems downloading:

> s3://endpoint/bucket/path

> s3:///bucket/path

> s3://key@endpoint/bucket/path

Only variant that worked for me was: 

> s3://bucket/path

**Comment by milos-ljubinkovic** [comment] 2017-11-02 17:59
In the 0.3.0 release of funnel I get a SYSTEM_ERROR task state without any additional logs that occurs after upload is started. The actual url I used in the output parameter:

>s3://testbunny/tes2/e54f0a4e-a1a1-416d-915b-7554d28537fb/root/step1/3

Same thing happens if I put a slash ( / ) at the end or if I try with a more direct folder structure: 
> s3://testbunny/tes3/

**Comment by adamstruck** [comment] 2017-11-02 18:25
Here is a simple example where I upload a directory to S3 that works for me:

```
{
  "outputs": [
    {
      "url": "s3://funnel-test/test-outputs",
      "path": "/opt/funnel/outputs",
      "type": "DIRECTORY"
    }
  ],
  "executors": [
    {
      "imageName": "alpine",
      "cmd": [
        "sh",
        "-c",
        "mkdir -p outputs/foo; touch outputs/foo/bar; echo hello > outputs/baz"
      ],
      "workdir": "/opt/funnel",
      "stdout": "/opt/funnel/outputs/stdout-0",
      "stderr": "/opt/funnel/outputs/stderr-0"
    }
  ]
}
```

In the above, both `s3://funnel-test/test-outputs` and `s3://funnel-test/test-outputs/` worked for me.

Does the bucket exist that your trying to upload to?

**Comment by milos-ljubinkovic** [comment] 2017-11-02 19:01
It exists. If I edit your example like this:
```
{
  "outputs": [
    {
      "url": "s3://testbunny/test-outputs",
      "path": "/opt/funnel/outputs",
      "type": "DIRECTORY"
    }
  ],  
  "inputs": [
    {
      "url": "s3://testbunny/input.txt",
      "path": "/opt/funnel/outputs/input.txt",
      "type": "FILE"
    }
  ],
  "executors": [
    {
      "imageName": "alpine",
      "cmd": [
        "sh",
        "-c",
        "mkdir -p outputs/foo; touch outputs/foo/bar; echo hello > outputs/baz"
      ],
      "workdir": "/opt/funnel",
      "stdout": "/opt/funnel/outputs/stdout-0",
      "stderr": "/opt/funnel/outputs/stderr-0"
    }
  ]
}
```

funnel successfully downloads the file
```
storage              Starting download
time                 2017-11-02T19:57:53+01:00
url                  s3://testbunny/input.txt

storage              Successfully saved
hostPath             /Users/milosljubinkovic/Downloads/funnel-work-dir/b7tmlb3lt51gh8sf1oig/opt/funnel/outputs/input.txt
time                 2017-11-02T19:57:54+01:00
```

But fails on upload:
```
storage              Starting upload
time                 2017-11-02T19:57:55+01:00
url                  s3://testbunny/test-outputs

server               Update task logs
time                 2017-11-02T19:57:55+01:00
unknown              &funnel.UpdateTaskLogsRequest{
    Id:      "b7tmlb3lt51gh8sf1oig",
    TaskLog: &tes.TaskLog{
        Logs:      nil,
        Metadata:  {},
        StartTime: "",
        EndTime:   "2017-11-02T19:57:55+01:00",
        Outputs:   nil,
    },
}

server               Update task STATE
time                 2017-11-02T19:57:55+01:00
unknown              &funnel.UpdateTaskStateRequest{Id:"b7tmlb3lt51gh8sf1oig", State:7}

server               Set task state
state                SYSTEM_ERROR
taskID               b7tmlb3lt51gh8sf1oig
time                 2017-11-02T19:57:55+01:00
```

**Comment by adamstruck** [comment] 2017-11-02 19:11
Your funnel logs don't look quite right to me - they appear to be from an old version.  Would you try downloading the [0.3.0 release](https://github.com/ohsu-comp-bio/funnel/releases/tag/0.3.0) and trying this again?

**Comment by milos-ljubinkovic** [comment] 2017-11-02 19:26
Yes, it was the funnel-darwin-386-0.3.0.tar.gz. It works with the amd64 version.

**Comment by buchanae** [comment] 2017-11-02 19:27
Sorry for the wasted effort. That was my fault for not doing a clean release.

**Comment by milos-ljubinkovic** [comment] 2017-11-02 22:37
It's no problem, really. I'm going to mess around with s3 a little bit more and then I'm going to make a new bunny and bunny-tes release.

Also, a quick question: do you see any possible problems that could arise in a bunny -> funnel -> SLURM configuration? (using s3 or google storage)

**Comment by adamstruck** [comment] 2017-11-02 23:10
That configuration should work fine.  Depending on the configuration of SLURM, you may need to change with the submit file template for SLURM in the configuration file for Funnel [example](https://ohsu-comp-bio.github.io/funnel/docs/guides/slurm/).  The problem we see most often is lack of docker access on compute nodes in these types of setups.

**Closed** 2017-11-08 14:09 UTC
